
name: "Prepare Environment"
description: "Installs/Updates necessary software and imports GPG key"

inputs:
  GPG_KEY:
    required: true
    description: "base64 of GPG key to import"

runs:
  using: "composite"

  steps:
  
  - name: Install/Update Software
    shell: bash
    run: |
      sudo snap remove firefox
      sudo apt update
      sudo apt upgrade
      sudo apt install reprepro dpkg-sig
    
  - name: Import GPG Key
    shell: bash
    run: |
      echo "$GPG_KEY" | base64 --decode | gpg --import
    env:
      GPG_KEY: ${{ inputs.GPG_KEY }}

