
name: "Prepare Environment"
description: "Installs/Updates necessary software and imports GPG key"

inputs:
  GPG_KEY:
    required: true
    description: "base64 of GPG key to import"

runs:
  using: "composite"

  steps:

  # we delete some packages before, as we dont need them, but they need to long to update
  - name: Install/Update Software
    shell: bash
    run: |
      sudo apt remove dotnet-sdk-6.0 dotnet-sdk-7.0 firefox dotnet-runtime-6.0 dotnet-runtime-7.0 powershell
      sudo apt update
      sudo apt upgrade
      sudo apt install reprepro dpkg-sig
    
  - name: Import GPG Key
    shell: bash
    run: |
      echo "$GPG_KEY" | base64 --decode | gpg --import
    env:
      GPG_KEY: ${{ inputs.GPG_KEY }}

