
name: Setup

on:
  workflow_call:

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install/Update Software
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install reprepro dpkg-sig
    
    - name: Import GPG Key
      run: |
        echo "$GPG_KEY" | base64 --decode | gpg --import
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
