
name: Update Packages

on:
  workflow_dispatch:
  schedule:
   - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install/Update Software
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install reprepro dpkg-sig
    
    - name: Import GPG Key
      run: |
        echo "$GPG_KEY" | base64 --decode | gpg --import
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}

    - name: Find vscodium Tag
      id: tag-vscodium
      run: |
        echo "TAG=$(curl https://api.github.com/repos/vscodium/vscodium/releases/latest 2>/dev/null | jq -r ".tag_name")" >>$GITHUB_OUTPUT

    - name: Download vscodium
      id: dl-vscodium
      run: |
        cd /tmp
        wget "https://github.com/VSCodium/vscodium/releases/download/${{ steps.tag-vscodium.outputs.TAG }}/codium_${{ steps.tag-vscodium.outputs.TAG }}_amd64.deb"
        wget "https://github.com/VSCodium/vscodium/releases/download/${{ steps.tag-vscodium.outputs.TAG }}/codium_${{ steps.tag-vscodium.outputs.TAG }}_amd64.deb.sha1"
        sha1sum -c "codium_${{ steps.tag-vscodium.outputs.TAG }}_amd64.deb"
        echo "DEBFILE=/tmp/codium_${{ steps.tag-vscodium.outputs.TAG }}_amd64.deb" >>$GITHUB_OUTPUT

    - name: Import vscodium
      run: |
        dpkg-sig -k "504FD21F8A4A753807873BC4E3E6A670D0C86417" --sign builder "${{ steps.dl-vscodium.outputs.DEBFILE }}"
        reprepro includedeb vera "${{ steps.dl-vscodium.outputs.DEBFILE }}"
    
    - name: Commit
      run: |
        git add .
        git commit -m "vscodium ${{ steps.tag-vscodium.outputs.TAG }}"
        git push
