
name: Update LF

on:
  workflow_dispatch:
  schedule:
   - cron: '0 3 1 * *'

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/prepare
      with:
        GPG_KEY: ${{ secrets.GPG_KEY }}

    - name: Find lf tag
      id: tag
      run: |
        echo "TAG=$(curl https://api.github.com/repos/gokcehan/lf/releases/latest 2>/dev/null | jq -r ".tag_name")" >>$GITHUB_OUTPUT

    - name: Download lf
      id: download
      run: |
        mkdir -vp /tmp/lf
        cd /tmp/lf
        wget "https://github.com/gokcehan/lf/releases/download/${{ steps.tag.outputs.TAG }}/lf-linux-amd64.tar.gz"
        tar xf "lf-linux-amd64.tar.gz"
        rm -vf "lf-linux-amd64.tar.gz"
        
        mkdir -vp DEBIAN
        cat >DEBIAN/control <<EOF
        Package: lf
        Version: $(echo "${{ steps.tag.outputs.TAG }}" | tr -d "r")
        Section: custom
        Priority: optional
        Architecture: amd64
        Essential: no
        Maintainer: alexcoder04
        Description: lf terminal file manager
        EOF
        mkdir -vp usr/bin
        mv lf usr/bin/lf
        chmod +x usr/bin/lf
        chmod 755 DEBIAN
        cd ..
        dpkg-deb --build lf
        mv "lf.deb" "lf_${{ steps.tag.outputs.TAG }}_amd64.deb"
        echo "DEBFILE=/tmp/lf_${{ steps.tag.outputs.TAG }}_amd64.deb" >>$GITHUB_OUTPUT

    - uses: ./.github/actions/commit
      with:
        FILE: "${{ steps.download.outputs.DEBFILE }}"
        GIT_EMAIL: ac04-dump@users.noreply.github.com
        GIT_NAME: ac04-dump
        MESSAGE: "lf ${{ steps.tag.outputs.TAG }}"

