
name: Update Codium

on:
  workflow_dispatch:
  schedule:
   - cron: '0 3 */3 * *'

env:
  GIT_USERNAME: ac04-dump
  GIT_EMAIL: alexcoder04@protonmail.com

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install/Update Software
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install reprepro dpkg-sig
    
    - name: Import GPG Key
      run: |
        echo "$GPG_KEY" | base64 --decode | gpg --import
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}

    - name: Find vscodium Tag
      id: tag-vscodium
      run: |
        echo "TAG=$(curl https://api.github.com/repos/vscodium/vscodium/releases/latest 2>/dev/null | jq -r ".tag_name")" >>$GITHUB_OUTPUT

    - name: Download vscodium
      id: dl-vscodium
      run: |
        cd /tmp
        wget "https://github.com/VSCodium/vscodium/releases/download/${{ steps.tag-vscodium.outputs.TAG }}/codium_${{ steps.tag-vscodium.outputs.TAG }}_amd64.deb"
        #wget "https://github.com/VSCodium/vscodium/releases/download/${{ steps.tag-vscodium.outputs.TAG }}/codium_${{ steps.tag-vscodium.outputs.TAG }}_amd64.deb.sha1"
        #[ "$(sha1sum "codium_${{ steps.tag-vscodium.outputs.TAG }}_amd64.deb" | cut -d " " -f1)" = "$(cut -d " " -f1 codium_${{ steps.tag-vscodium.outputs.TAG }}_amd64.deb.sha1)" ]
        echo "DEBFILE=/tmp/codium_${{ steps.tag-vscodium.outputs.TAG }}_amd64.deb" >>$GITHUB_OUTPUT

    - name: Import vscodium
      run: |
        [ -f "pool/main/c/codium/$(basename ${{ steps.dl-vscodium.outputs.DEBFILE }})" ] && exit
        dpkg-sig -k "504FD21F8A4A753807873BC4E3E6A670D0C86417" --sign builder "${{ steps.dl-vscodium.outputs.DEBFILE }}"
        reprepro includedeb vera "${{ steps.dl-vscodium.outputs.DEBFILE }}"

    - name: Commit
      run: |
        [ -z "$(git status -s)" ] && exit
        git config --global user.email "$GIT_EMAIL"
        git config --global user.name "$GIT_USERNAME"
        git add .
        git commit -m "vscodium ${{ steps.tag-vscodium.outputs.TAG }}"
        git push

