
name: Update Packages

on:
  workflow_dispatch:
  schedule:
   - cron: '0 0 * * *'

jobs:
  codium:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install/Update Software
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install reprepro dpkg-sig
    
    - name: Import GPG Key
      run: |
        echo "$GPG_KEY" | base64 --decode | gpg --import
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}

    - name: Find vscodium Tag
      id: tag-vscodium
      run: |
        echo "TAG=$(curl https://api.github.com/repos/vscodium/vscodium/releases/latest 2>/dev/null | jq -r ".tag_name")" >>$GITHUB_OUTPUT

    - name: Download vscodium
      id: dl-vscodium
      run: |
        cd /tmp
        wget "https://github.com/VSCodium/vscodium/releases/download/${{ steps.tag-vscodium.outputs.TAG }}/codium_${{ steps.tag-vscodium.outputs.TAG }}_amd64.deb"
        #wget "https://github.com/VSCodium/vscodium/releases/download/${{ steps.tag-vscodium.outputs.TAG }}/codium_${{ steps.tag-vscodium.outputs.TAG }}_amd64.deb.sha1"
        #[ "$(sha1sum "codium_${{ steps.tag-vscodium.outputs.TAG }}_amd64.deb" | cut -d " " -f1)" = "$(cut -d " " -f1 codium_${{ steps.tag-vscodium.outputs.TAG }}_amd64.deb.sha1)" ]
        echo "DEBFILE=/tmp/codium_${{ steps.tag-vscodium.outputs.TAG }}_amd64.deb" >>$GITHUB_OUTPUT

    - name: Import vscodium
      run: |
        [ -f "pool/main/c/codium/$(basename ${{ steps.dl-vscodium.outputs.DEBFILE }})" ] && exit
        dpkg-sig -k "504FD21F8A4A753807873BC4E3E6A670D0C86417" --sign builder "${{ steps.dl-vscodium.outputs.DEBFILE }}"
        reprepro includedeb vera "${{ steps.dl-vscodium.outputs.DEBFILE }}"

    - name: Commit
      run: |
        git config --global user.email "alexcoder04@protonmail.com"
        git config --global user.name "alexcoder04"
        git add .
        git commit -m "vscodium ${{ steps.tag-vscodium.outputs.TAG }}"
        git push


  lf:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Install/Update Software
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt install reprepro dpkg-sig
    
    - name: Import GPG Key
      run: |
        echo "$GPG_KEY" | base64 --decode | gpg --import
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}

    - name: Find lf tag
      id: tag-lf
      run: |
        echo "TAG=$(curl https://api.github.com/repos/gokcehan/lf/releases/latest 2>/dev/null | jq -r ".tag_name")" >>$GITHUB_OUTPUT

    - name: Download lf
      id: dl-lf
      run: |
        mkdir -vp /tmp/lf
        cd /tmp/lf
        wget "https://github.com/gokcehan/lf/releases/download/${{ steps.tag-lf.outputs.TAG }}/lf-linux-amd64.tar.gz"
        tar xf "lf-linux-amd64.tar.gz"
        rm -vf "lf-linux-amd64.tar.gz"
        mkdir -vp DEBIAN
        cat >DEBIAN/control <<EOF
        Package: lf
        Version: $(echo "${{ steps.tag-lf.outputs.TAG }}" | tr -d "r")
        Section: custom
        Priority: optional
        Architecture: amd64
        Essential: no
        Maintainer: alexcoder04
        Description: lf terminal file manager
        EOF
        mkdir -vp usr/bin
        mv lf usr/bin/lf
        chmod +x usr/bin/lf
        chmod 755 DEBIAN
        cd ..
        dpkg-deb --build lf
        echo "DEBFILE=/tmp/lf.deb" >>$GITHUB_OUTPUT

    - name: Import lf
      run: |
        [ -f "pool/main/l/lf/$(basename "${{ steps.dl-lf.outputs.DEBFILE }}")" ] && exit
        dpkg-sig -k "504FD21F8A4A753807873BC4E3E6A670D0C86417" --sign builder "${{ steps.dl-lf.outputs.DEBFILE }}"
        reprepro includedeb vera "${{ steps.dl-lf.outputs.DEBFILE }}"

    - name: Commit
      run: |
        git config --global user.email "alexcoder04@protonmail.com"
        git config --global user.name "alexcoder04"
        git add .
        git commit -m "vscodium ${{ steps.tag-vscodium.outputs.TAG }}"
        git push
